MvcMovieProject/MvcMovieProject/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovieProject.Data;
using MvcMovieProject.Models;
using MvcMovieProject.Models.MovieViewModels;

namespace MvcMovieProject.Controllers
{
    public class ActorsController : Controller
    {
        private readonly MvcMovieProjectContext _context;

        public ActorsController(MvcMovieProjectContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["LocationSortParm"] = sortOrder == "Home Town" ? "location_desc" : "Home Town";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var actors = from a in _context.Actor
                         select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                actors = actors.Where(s => (s.Name).Contains(searchString));
            }

            actors = Sort(sortOrder, actors);

            int pageSize = 10; 
            return View(await PaginatedList<Actor>.CreateAsync(actors.AsNoTracking(), page ?? 1, pageSize));
        }

        private IQueryable<Actor> Sort(string sortOrder, IQueryable<Actor> actors)
        {
            switch(sortOrder)
            {
                case "name_desc":
                    actors = actors.OrderByDescending(s => s.Name);
                    break;
                case "Home Town":
                    actors = actors.OrderBy(s => s.HomeTown);
                    break;
                case "location_desc":
                    actors = actors.OrderByDescending(s => s.HomeTown);
                    break;
                default:
                    actors = actors.OrderBy(s => s.Name);
                    break;
            }

            return (actors);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .SingleOrDefaultAsync(m => m.ActorID == id);
            if (actor == null)
            {
                return NotFound();
            }

            ActorIndexViewData viewModel = new ActorIndexViewData();
            var movies = from role in _context.MovieRole
                             where role.ActorID == id
                             select role.Movie;
            var movieRoles = from role in _context.MovieRole
                             where role.ActorID == id
                             select role;
            viewModel.Movies = movies;
            viewModel.Actor = actor;
            viewModel.MovieRoles = movieRoles;

            return View(viewModel);
        }
    

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActorID,Name, BirthName, BirthDate, HomeTown")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.SingleOrDefaultAsync(m => m.ActorID == id);
            if (actor == null)
            {
                return NotFound();
            }

            ActorRoleAdditionData viewModel = new ActorRoleAdditionData();
            ActorIndexViewData actorIndexViewData = new ActorIndexViewData();
            var allMovies = from movie in _context.Movie
                            select movie.Title;
            var movies = from role in _context.MovieRole
                         where role.ActorID == id
                         select role.Movie;
            var movieRoles = from role in _context.MovieRole
                             where role.ActorID == id
                             select role;
            viewModel.Movies = new SelectList(await allMovies.ToListAsync());
            actorIndexViewData.Movies = movies;
            actorIndexViewData.Actor = actor;
            actorIndexViewData.MovieRoles = movieRoles;
            viewModel.ActorIndexViewData = actorIndexViewData;

            return View(viewModel);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ActorID, Name, BirthName, BirthDate, HomeTown")] Actor actor)
        {
            if (id != actor.ActorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ActorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .SingleOrDefaultAsync(m => m.ActorID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actor.SingleOrDefaultAsync(m => m.ActorID == id);
            _context.Actor.Remove(actor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public JsonResult GetModel(int id)
        {
            Console.WriteLine(id);
            var movies = (from movie in _context.Movie
                         orderby movie.Title
                        select movie).Distinct().ToList();
            var roles = (from role in _context.MovieRole
                         where role.ActorID == id
                         select role.Movie).Distinct().ToList();
            var model = movies.Where(x => !(roles.Contains(x)) == true).ToList();
            foreach(var i in model) { Console.WriteLine(i.Title); }
            return Json(model);
        }
        
        [HttpPost]
        public async Task<JsonResult> SaveRow([Bind("MovieRoleID,ActorID,MovieID,Character")] MovieRole movieRole)
        {
            
            if (ModelState.IsValid)
            {
                
                _context.Add(movieRole);
                await _context.SaveChangesAsync();


            }

            var query = await (from movie in _context.Movie
                        where movie.ID == movieRole.MovieID
                        select movie).FirstOrDefaultAsync();

            IDictionary<string, string> jsonObject = new Dictionary<string, string>()
            {
                {"Title", query.Title },
                {"Character", movieRole.Character },
                {"MovieRoleID", movieRole.MovieRoleID.ToString() }
            };

            return Json(jsonObject);
        }

        private bool ActorExists(int id)
        {
            return _context.Actor.Any(e => e.ActorID == id);
        }
    }
}

MvcMovieProject/MvcMovieProject/Controllers/MovieRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovieProject.Data;
using MvcMovieProject.Models;

namespace MvcMovieProject.Controllers
{
    public class MovieRolesController : Controller
    {
        private readonly MvcMovieProjectContext _context;

        public MovieRolesController(MvcMovieProjectContext context)
        {
            _context = context;
        }

        // GET: MovieRoles
        public async Task<IActionResult> Index()
        {
            var mvcMovieProjectContext = _context.MovieRole.Include(m => m.Actor).Include(m => m.Movie);
            return View(await mvcMovieProjectContext.ToListAsync());
        }

        // GET: MovieRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieRole = await _context.MovieRole
                .Include(m => m.Actor)
                .Include(m => m.Movie)
                .SingleOrDefaultAsync(m => m.MovieRoleID == id);
            if (movieRole == null)
            {
                return NotFound();
            }

            return View(movieRole);
        }

        // GET: MovieRoles/Create
        public IActionResult Create()
        {
            ViewData["ActorID"] = new SelectList(_context.Actor, "ActorID", "Name");
            ViewData["MovieID"] = new SelectList(_context.Movie, "ID", "Genre");
            return View();
        }

        // POST: MovieRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieRoleID,ActorID,MovieID,Character")] MovieRole movieRole)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movieRole);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorID"] = new SelectList(_context.Actor, "ActorID", "Name", movieRole.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movie, "ID", "Genre", movieRole.MovieID);
            return View(movieRole);
        }

        // GET: MovieRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieRole = await _context.MovieRole.SingleOrDefaultAsync(m => m.MovieRoleID == id);
            if (movieRole == null)
            {
                return NotFound();
            }
            ViewData["ActorID"] = new SelectList(_context.Actor, "ActorID", "Name", movieRole.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movie, "ID", "Genre", movieRole.MovieID);
            return View(movieRole);
        }

        // POST: MovieRoles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieRoleID,ActorID,MovieID,Character")] MovieRole movieRole)
        {
            if (id != movieRole.MovieRoleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movieRole);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieRoleExists(movieRole.MovieRoleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorID"] = new SelectList(_context.Actor, "ActorID", "Name", movieRole.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movie, "ID", "Genre", movieRole.MovieID);
            return View(movieRole);
        }

        // GET: MovieRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieRole = await _context.MovieRole
                .Include(m => m.Actor)
                .Include(m => m.Movie)
                .SingleOrDefaultAsync(m => m.MovieRoleID == id);
            if (movieRole == null)
            {
                return NotFound();
            }

            return View(movieRole);
        }

        // POST: MovieRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movieRole = await _context.MovieRole.SingleOrDefaultAsync(m => m.MovieRoleID == id);
            _context.MovieRole.Remove(movieRole);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieRoleExists(int id)
        {
            return _context.MovieRole.Any(e => e.MovieRoleID == id);
        }
    }
}

MvcMovieProject/MvcMovieProject/Views/Movies/Create.cshtml
@model MvcMovieProject.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovieProject/MvcMovieProject/Views/Movies/Delete.cshtml
@model MvcMovieProject.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.Title)</h4>
    <hr />
    <div class="col-md-4">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReleaseDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Genre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Rating)
            </dd>
        </dl>
    </div>
    <div class="col-md-8">
        <img src="@Model.Image" alt="@Model.Title" height="250" width="150" />
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcMovieProject/MvcMovieProject/Views/Movies/Details.cshtml
@model MvcMovieProject.MovieViewModels.Models.MovieIndexData

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Movie.Title)</h4>
    <hr />
    <div class="container-fluid">
    <div class="col-md-4">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Movie.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.ReleaseDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Movie.Genre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Genre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Movie.Price)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Price)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Movie.Rating)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Rating)
            </dd>
        </dl>
    </div>
    <div class="col-md-4">
        <img src="@Model.Movie.Image" alt="@Model.Movie.Title" height="250" width="200" />
    </div>
    <div class="col-md-4">

    @if(Model.Actors != null)
    {
        <table class="table">
            <tr>
                <th>Actor</th>
                <th>Character</th>
            </tr>
            @foreach(var actor in Model.Actors)
            {
                <tr>
                    <td>@actor.Name</td>

                    @foreach(var role in Model.MovieRoles)
                    {
                        if(role.ActorID == actor.ActorID)
                        {
                            <td>@role.Character</td>

                        }

                    }
                </tr>
                

            }
        </table>

    }
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>
</div>

MvcMovieProject/MvcMovieProject/Views/Movies/Edit.cshtml
@model MvcMovieProject.MovieViewModels.Models.MovieIndexData
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/MovieEdit.js"></script>
<script src="~/js/MovieIndex.js"></script>
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>@Html.DisplayFor(model => model.Movie.Title)</h4>
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Movie.Title" class="control-label"></label>
                    <input asp-for="Movie.Title" class="form-control" />
                    <span asp-validation-for="Movie.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                    <input asp-for="Movie.ReleaseDate" class="form-control" />
                    <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Genre" class="control-label"></label>
                    <input asp-for="Movie.Genre" class="form-control" />
                    <span asp-validation-for="Movie.Genre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Price" class="control-label"></label>
                    <input asp-for="Movie.Price" class="form-control" />
                    <span asp-validation-for="Movie.Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Rating" class="control-label"></label>
                    <input asp-for="Movie.Rating" class="form-control" />
                    <span asp-validation-for="Movie.Rating" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Movie.Image" class="control-label"></label>
                    <input asp-for="Movie.Image" class="form-control" />
                    <span asp-validation-for="Movie.Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
        <div class="col-md-4">
            <img src="@Model.Movie.Image" alt="@Model.Movie.Title" />
        </div>
        <div class="col-md-4">

            <h4>Movie Roles</h4>
            <a href="#" id="role_add" data-role="@Model.Movie.ID">Add Movie Role</a>
            <form id="role_form" action="Edit" method="post">
                <input type="hidden" value="@Model.Movie.ID" name="MovieID" />
                <table class="table">
                    <tr>
                        <th>Actor</th>
                        <th>Character</th>
                        <th></th>
                    </tr>
                    <tbody id="role_table">
                        @if (Model.Actors != null)
                        {
                            @foreach (var actor in Model.Actors)
                            {
                                <tr>
                                    <td>@actor.Name</td>

                                    @foreach (var role in Model.MovieRoles)
                                    {
                                        if (role.ActorID == actor.ActorID)
                                        {
                                            <td>@role.Character</td>
                                            //creates button for submitting the movie ID and the MovieRoleID for each actors role
                                            <td>
                                                <a asp-controller="MovieRoles" asp-action="Delete" asp-route-id="@role.MovieRoleID">Delete</a>
                                            </td>

                                        }


                                    }
                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </form>

        </div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovieProject/MvcMovieProject/Views/Movies/Index.cshtml
@model MvcMovieProject.MovieViewModels.Models.MovieGenreViewModel
<link href="~/css/StyleSheet.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript" src="~/js/MovieIndex.js"></script>
@{
    ViewData["Title"] = "Movies";
}

<h2>Movies</h2>


<p>
    <a asp-action="Create">Add New Movie</a>
</p>

<form asp-controller="Movies" asp-action="Index" method="get">
    <p>
        <select asp-for="movieGenre" asp-items="Model.genres">
            <option value="">All</option>
        </select>
        Title: <input type="text" name="movieSearch" value="@ViewData["MovieFilter"]" />
        Actor: <input type="text" name="actorSearch" value="@ViewData["ActorFilter"]" />
        <input type="submit" value="Search" class="btn btn-default" /> |
        <a asp-action="Index" value="">Back to Full List</a>
    </p>
</form>
<table class="table" id="movieTable">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParm"]" asp-route-actorFilter="@ViewData["ActorFilter"]" asp-route-movieFilter="@ViewData["MovieFilter"]">@Html.DisplayNameFor(model => model.movies[0].Title)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-actorFilter="@ViewData["ActorFilter"]" asp-route-movieFilter="@ViewData["MovieFilter"]">@Html.DisplayNameFor(model => model.movies[0].ReleaseDate)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["GenreSortParm"]" asp-route-actorFilter="@ViewData["ActorFilter"]" asp-route-movieFilter="@ViewData["MovieFilter"]">@Html.DisplayNameFor(model => model.movies[0].Genre)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]" asp-route-actorFilter="@ViewData["ActorFilter"]" asp-route-movieFilter="@ViewData["MovieFilter"]">@Html.DisplayNameFor(model => model.movies[0].Price)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["RatingSortParm"]" asp-route-actorFilter="@ViewData["ActorFilter"]" asp-route-movieFilter="@ViewData["MovieFilter"]">@Html.DisplayNameFor(model => model.movies[0].Rating)</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model.PageList)
        {
            string selectedRow = "";
            if (item.ID == (int?)ViewData["MovieID"])
            {
                selectedRow = "success";


            }
            <tr class="@selectedRow clickable-row" onclick="location.href='@Url.Action("Index", "Movies", new {id = @item.ID })'">
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">
                        <img src="@item.Image" alt="@item.Title" height="200" width="150" />
                    </a>
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a asp-action="Index" asp-route-id="@item.ID" asp-route-sortOrder="@ViewData["CurrentSort"]" 
                       asp-route-actorSearch="@ViewData["ActorFilter"]" asp-route-movieSearch="@ViewData["MovieFilter"]" 
                       asp-route-page="@ViewData["CurrentPage"]">Select</a> |
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
            }
</tbody>
</table>

@if (Model.MovieIndexData.Actors != null)
{
    var id = (from i in Model.MovieIndexData.Movies
              where Model.MovieIndexData.ID == i.ID
              select i).FirstOrDefault();
    <h3>Cast of @id.Title</h3>
    <table class="table">
        <tr>
            <th>Actor</th>
            <th>Character</th>
        </tr>

        @foreach (var item in Model.MovieIndexData.Actors)
        {
            <tr>
                <td>
                    <a asp-controller="Actors" asp-action="Details" asp-route-id="@item.ActorID">@item.Name</a>
                </td>
                @foreach (var role in Model.MovieIndexData.MovieRoles)
                {
                    if (role.ActorID == item.ActorID)
                    {
                        <td>@role.Character </td>

                    }

                }

            </tr>
        }

    </table>
    ViewData["MovieID"] = null;

}

@{
    var prevDisabled = !Model.PageList.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.PageList.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageList.PageIndex - 1)"
   asp-route-actorFilter="@ViewData["ActorFilter"]"
   asp-route-movieFilter="@ViewData["MovieFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageList.PageIndex + 1)"
   asp-route-actorFilter="@ViewData["ActorFilter"]"
   asp-route-movieFilter="@ViewData["MovieFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>